version: "2017-09-20"
pipeline:
- id: build-push
  overlay: ci/java
  type: script
  commands:
  - desc: checkstyle
    cmd: |
      ./gradlew checkstyle --stacktrace
  - desc: test
    cmd: |
      ./gradlew testWithReport --stacktrace
  - desc: acceptance-test
    cmd: |
      ./gradlew fullAcceptanceTest --stacktrace
  - desc: push
    cmd: |
      ./gradlew clen bootRepackage
      if [ "$CDP_PULL_REQUEST_NUMBER" ]; then
        IMAGE="registry-write.opensource.zalan.do/aruha/nakadi-oss:${CDP_BUILD_VERSION}"
      else
        IMAGE="registry-write.opensource.zalan.do/aruha/nakadi-oss-test:${CDP_BUILD_VERSION}"
      fi
      docker build -t ${IMAGE} .
      docker push ${IMAGE}
