version: "2017-09-20"
pipeline:
- id: build-push
  overlay: ci/java
  type: script
  commands:
  - desc: Install dependencies
    cmd: |
      pip install docker-compose==1.24.1
  - desc: Checkstyle
    cmd: |
      ./gradlew checkstyle --stacktrace
  - desc: Test
    cmd: |
      ./gradlew testWithReport --stacktrace
  - desc: Acceptance Test
    cmd: |
      ./gradlew fullAcceptanceTest --stacktrace
  - desc: Push to repo
    cmd: |
      ./gradlew clean bootRepackage
      if [ "$CDP_PULL_REQUEST_NUMBER" ]; then
        IMAGE="registry-write.opensource.zalan.do/aruha/nakadi-oss:${CDP_BUILD_VERSION}"
      else
        IMAGE="registry-write.opensource.zalan.do/aruha/nakadi-oss-test:${CDP_BUILD_VERSION}"
      fi
      docker build -t ${IMAGE} .
      docker push ${IMAGE}
